In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
population_dataset = pd.read_csv("NST-EST2015-alldata.csv")

In [3]:
#Write a Python program to read the CSV file and output each state, ordered from highest to lowest estimated population in 2015
result_df = population_dataset[ (population_dataset['SUMLEV'] == 40)].sort_values('POPESTIMATE2015', ascending=False)
result_df.head()

,SUMLEV,REGION,DIVISION,STATE,NAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
9,40,4,9,6,California,37253956,37254503,37334079,37700034,38056055,...,-1.148464,-1.163788,-1.339869,-0.862856,-1.981572,2.761704,2.647127,2.728645,3.743342,2.656065
48,40,3,7,48,Texas,25145561,25146105,25244363,25654464,26089741,...,4.527491,5.484904,4.446476,6.072953,6.248252,7.616364,8.660719,7.739851,9.780487,9.978697
14,40,3,5,12,Florida,18801310,18804623,18849890,19105533,19352021,...,5.556307,5.138184,4.847420,6.958576,10.080932,11.364173,10.676030,10.565882,13.478570,16.528676
37,40,1,2,36,New York,19378102,19378087,19402920,19523202,19606981,...,-4.354557,-5.945385,-5.561401,-8.130297,-7.990563,1.439239,-0.402860,0.407960,-1.334639,-1.205321
18,40,2,3,17,Illinois,12830632,12831549,12841249,12861882,12875167,...,-5.243330,-5.805172,-5.308960,-7.509147,-8.174675,-3.020410,-3.519051,-2.830379,-4.625216,-5.247030

In [5]:
result_df[['NAME','POPESTIMATE2015', 'POPESTIMATE2014', 'POPESTIMATE2013', 'POPESTIMATE2012', 'POPESTIMATE2011', 'POPESTIMATE2010']]

,NAME,POPESTIMATE2015,POPESTIMATE2014,POPESTIMATE2013,POPESTIMATE2012,POPESTIMATE2011,POPESTIMATE2010
9,California,39144818,38792291,38414128,38056055,37700034,37334079
48,Texas,27469114,26979078,26500674,26089741,25654464,25244363
14,Florida,20271272,19905569,19594467,19352021,19105533,18849890
37,New York,19795791,19748858,19691032,19606981,19523202,19402920
18,Illinois,12859995,12882189,12889580,12875167,12861882,12841249
43,Pennsylvania,12802503,12793767,12783536,12772789,12745202,12712014
40,Ohio,11613423,11596998,11572232,11551783,11545442,11540766
15,Georgia,10214860,10097132,9991562,9917639,9812280,9713454
38,North Carolina,10042802,9940387,9845432,9747021,9651025,9558979
27,Michigan,9922576,9916306,9900506,9886879,9876589,9877369
35,New Jersey,8958013,8938844,8907384,8874893,8842934,8803881
51,Virginia,8382993,8328098,8267875,8193374,8110783,8025787
52,Washington,7170351,7063166,6973281,6897292,6823229,6743060
7,Arizona,6828065,6728783,6630799,6553262,6468732,6408208
26,Massachusetts,6794422,6755124,6708810,6657780,6611797,6565036
19,Indiana,6619680,6597880,6570518,6538283,6516845,6490590
47,Tennessee,6600299,6547779,6496130,6455469,6398408,6356585
30,Missouri,6083672,6063827,6043708,6025468,6010587,5996052
25,Maryland,6006401,5975346,5936040,5890740,5844171,5788409
54,Wisconsin,5771337,5759432,5743653,5726422,5709720,5690204
28,Minnesota,5489594,5457125,5420541,5380443,5348119,5310903
10,Colorado,5456574,5355588,5271132,5191731,5119480,5048254
45,South Carolina,4896146,4829160,4768498,4721341,4672733,4635894
5,Alabama,4858979,4846411,4830533,4816089,4801108,4785161
23,Louisiana,4670724,4648990,4627491,4603676,4575381,4544951
22,Kentucky,4425092,4412617,4398500,4382667,4367882,4347937
42,Oregon,4028977,3971202,3928030,3899444,3868509,3837972
41,Oklahoma,3911338,3879610,3853405,3817679,3786626,3759596
11,Connecticut,3590886,3594762,3597168,3593541,3589759,3579717
56,Puerto Rico,3474182,3534888,3593079,3634487,3678736,3721526
20,Iowa,3123899,3109481,3092224,3076636,3065389,3050694
49,Utah,2995919,2944498,2903685,2856343,2816440,2775426
29,Mississippi,2992333,2993443,2990976,2985660,2977999,2970316
8,Arkansas,2978204,2966835,2957957,2949499,2938538,2922394
21,Kansas,2911641,2902507,2894630,2886281,2869917,2858824
33,Nevada,2890845,2838281,2790366,2754874,2718819,2703440
36,New Mexico,2085109,2085567,2086890,2084792,2078226,2064741
32,Nebraska,1896190,1882980,1869300,1855973,1842383,1830025
53,West Virginia,1844128,1848751,1852985,1856283,1854948,1854225
17,Idaho,1654930,1634806,1612785,1596097,1584134,1570986
16,Hawaii,1431603,1420257,1408765,1392641,1378227,1363980
34,New Hampshire,1330608,1327996,1322660,1321393,1318344,1316708
24,Maine,1329328,1330256,1328778,1328888,1328257,1327695
44,Rhode Island,1056298,1054907,1052856,1052393,1051856,1053219
31,Montana,1032949,1023252,1014402,1005157,997746,990643
12,Delaware,945934,935968,925353,917099,907916,899791
46,South Dakota,858469,853304,845270,834631,824289,816299
39,North Dakota,756927,740040,723626,702265,685326,674530
6,Alaska,738432,737046,737442,731228,722720,714021
13,District of Columbia,672228,659836,649540,635342,620472,605126
50,Vermont,626042,626767,627129,626398,626687,625984
55,Wyoming,586107,584304,583131,577080,567768,564516